### ISSUE TITLE
[iOS] No known instance method for selector 'shouldAutorotateToInterfaceOrientation:'

### ISSUE THREAD

**Issue by mosabab** [apache/cordova-plugin-inappbrowser#714]
# Bug Report

## Problem
Xcode v11.5 show this error:
No known instance method for selector 'shouldAutorotateToInterfaceOrientation:'

### What is expected to happen?
The error should not appear in Xcode.

### What does actually happen?
When you try to build your code either from command line at macOS:

`cordova build ios`

The following build commands failed:
CompileC /var/root/Library/Developer/Xcode/DerivedData/myapp-fwtbwlotgipnwyfynxipdyoqnfgg/Build/Intermediates.noindex/myapp.build/Debug-iphonesimulator/testapp.build/Objects-normal/x86_64/CDVWKInAppBrowser.o /Users/mosab/Documents/myapp/platforms/ios/testapp/Plugins/cordova-plugin-inappbrowser/CDVWKInAppBrowser.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

--
And if you open your project in Xcode, you will see the following error message:
/Users/mosab/Documents/myapp/platforms/ios/testapp/Plugins/cordova-plugin-inappbrowser/CDVWKInAppBrowser.m:1250:42: No known instance method for selector 'shouldAutorotateToInterfaceOrientation:'

### Command or Code

cordova build ios

### Environment, Platform, Device

iOS

### Version information

cordova cli 9.0.0
cordova-ios 6.0.0
cordova-plugin-inappbrowser (master version) or 3.2.0
Xcode 11.5
macOS 10.15.5

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
> cordova-plugin-inappbrowser (master version) or 3.2.0

Did you test both master (`4.0.0-dev`) and `3.2.0`?

I believe this is the known issue that `4.0.0-dev` is suppose to resolve.

**Comment by mosabab** [comment]
> > cordova-plugin-inappbrowser (master version) or 3.2.0
> 
> Did you test both master (`4.0.0-dev`) and `3.2.0`?
> 
> I believe this is a known issue that `4.0.0-dev` is suppose to resolve.

I test it in this versions:

First test:
https://github.com/apache/cordova-plugin-inappbrowser.git#master

Second test
https://github.com/apache/cordova-plugin-inappbrowser.git#3.2.0

I think the problem from line CDVWKInAppBrowser.m:1250:42

Because I am using Xcode 11.5

Maybe the other users not testing in new versions of Xcode.

**Comment by asgeo1** [comment]
Having this issue too on `master`. It's because `shouldAutorotateToInterfaceOrientation` is depreciated and doesn't work with cordova-ios `6.0.0`

The issue was originally fixed in this PR: https://github.com/apache/cordova-plugin-inappbrowser/pull/666

Then for some reason in this PR the change was reversed: https://github.com/apache/cordova-plugin-inappbrowser/pull/656

Suggest that the original fix is reinstated...

**Comment by breautek** [comment]
Thanks @asgeo1 for pointing that out.

**Comment by mosabab** [comment]
> Having this issue too on `master`. It's because `shouldAutorotateToInterfaceOrientation` is depreciated and doesn't work with cordova-ios `6.0.0`
> 
> The issue was originally fixed in this PR: #666
> 
> Then for some reason in this PR the change was reversed: #656
> 
> Suggest that the original fix is reinstated.

You are right
Thanks for info

**Comment by NiklasMerz** [comment]
I just submitted a PR that should fix that again. Thank you for spotting the issue.

Reviews are welcome `https://github.com/apache/cordova-plugin-inappbrowser.git#fix-regression-656`

**Comment by mosabab** [comment]
> I just submitted a PR that should fix that again. Thank you for spotting the issue.
> 
> Reviews are welcome `https://github.com/apache/cordova-plugin-inappbrowser.git#fix-regression-656`

Thank you

**Comment by antikalk** [comment]
I am having the same issue. Using the PR solves the error for me. :)

**Comment by DaedalusAB** [comment]
I still have this issue on xCode 11.7 and plugin version 4.0.0
I assume the PR with fix was merged?

**Comment by isipisi281** [comment]
Same here.

**Comment by zulkarnainshah** [comment]
Whats is the solution now?

**Comment by NiklasMerz** [comment]
Please use the latest  versions of the plugin, cordova-ios and Xcode if possible. If you still got any issues please open a new issues with a complete error log.
